export const coreBehaviors: string[] = [
  "Social Engineering",
  "Malware",
  "Removable Media",
  "Physical Security",
  "Working Remotely",
  "Mobile Security",
  "Safe Web Browsing",
];

export const contentTypes: string[] = [
  "Assessment",
  "Training Module",
  "Live-Action Video",
  "Publishing Assistant Module",
  "Program Resource",
  "Game",
];

export const languages = [
  { label: "Arabic", value: "ar" },
  { label: "Hindi - HI", value: "HI" },
  { label: "Urdu - UR", value: "UR" },
  { label: "Swedish", value: "sv" },
  { label: "Slovenian - SL", value: "sl" },
  { label: "Romanian", value: "ro" },
  { label: "Slovak", value: "sk" },
  { label: "Spanish", value: "es" },
  { label: "Lithuanian", value: "lt" },
  { label: "Latvian", value: "lv" },
  { label: "Portuguese", value: "pt" },
  { label: "Italian", value: "it" },
  { label: "Polish", value: "pl" },
  { label: "Irish", value: "ga" },
  { label: "Hungarian", value: "hu" },
  { label: "French", value: "fr" },
  { label: "German", value: "de" },
  { label: "Greek", value: "el" },
  { label: "Czech", value: "cs" },
  { label: "Estonian", value: "et" },
  { label: "Dutch", value: "nl" },
  { label: "Finnish", value: "fi" },
  { label: "Danish", value: "da" },
  { label: "English", value: "en" },
];

export const categories: string[] = [
  "Administrative Modules",
  "Advanced Cybersecurity and Risk Management",
  "Compliance",
  "GDPR",
  "K-12",
  "Malware & Phishing",
  "Mobile Security",
  "Network Security",
  "Password Security",
  "Personnel Security",
  "Physical Security & Hardware",
  "Privacy and Data Protection",
  "Secure Application Development",
  "Social Engineering",
  "Web-Based Threats",
];

export const roles: string[] = [
  "Customer service",
  "Developers",
  "Executives",
  "Finance",
  "General",
  "Human Resources",
  "IT Staff",
  "Managers",
  "Privileged users",
];

export const industries: string[] = [
  "Critical Infrastructure",
  "Education",
  "Financial Services",
  "Government",
  "Healthcare",
  "Manufacturing",
  "Not for Profit",
  "Other",
  "Retail",
  "Technology",
];

export const durations: string[] = [
  "Under 2 Minutes",
  "2-5 Minutes",
  "5-10 Minutes",
  "Over 10 Minutes",
];

export const tags: string[] = [
  "Acceptable Use Policy",
  "Access Control",
  "Accessible",
  "AI",
  "Antivirus",
  "API",
  "App Permissions",
  "APT",
  "Attachments",
  "Attack Prevention",
  "Authentication",
  "Backups",
  "Bank Secrecy Act",
  "Banking Trojans",
  "Basic Information",
  "Business Email Compromise",
  "C-I-A Triad",
  "C-TPAT",
  "CCPA",
  "CJI",
  "Cloud Security",
  "CMMC",
  "COPPA",
  "Core Concepts",
  "CPNI",
  "Cross-Site Scripting",
  "CSAM",
  "CSRF",
  "Cybersecurity",
  "Cybersecurity Awareness Month",
  "Data Destruction",
  "Data Disclosure",
  "Data Disposal",
  "Data Protection",
  "Data Storage",
  "Deserialization",
  "Device Theft",
  "DFARS",
  "EAL",
  "Educator",
  "Email",
  "Encryption",
  "Error Handling",
  "FAR Code of Conduct",
  "FCPA",
  "FERPA",
  "FINRA",
  "Firewall",
  "Fraud Prevention",
  "FTI",
  "GDPR",
  "GLBA",
  "Hacked for the Holidays",
  "Hacker Headlines",
  "HIPAA",
  "HITECH",
  "Host Name",
  "HTTPS",
  "Identity Theft",
  "Incident Response",
  "Infringement Risks",
  "Injection Flaws",
  "Insider Threat",
  "Intellectual Property",
  "Interactive",
  "Introduction",
  "IoT Security",
  "Just the Facts",
  "K-12",
  "Legislation",
  "License agreement",
  "Links",
  "Live Action",
  "Logging and Monitoring",
  "Malware",
  "Manager",
  "Marine Lowlifes",
  "Medical Devices",
  "Microlearning",
  "Misconfiguration",
  "Mobile Security",
  "Money Laundering",
  "Multi-Factor Authentication",
  "Need to Know: Season 1",
  "Need to Know: Season 2",
  "Network Security",
  "NIST",
  "Organizational Policy",
  "OWASP",
  "Password Security",
  "PCI",
  "Permissions",
  "Personal Data",
  "PHI",
  "Phishing",
  "Physical Security",
  "Pick Your Path",
  "PII",
  "Pretexting",
  "Privacy",
  "Proper Disposal",
  "Public Networks",
  "Ransomware",
  "Red Flags Rule",
  "Regulation",
  "Remote Access",
  "Removable Media",
  "Report Attacks",
  "Role-Based Training",
  "Safe Browsing",
  "Safe Data Handling",
  "Sarbanes-Oxley Act",
  "Secure Coding",
  "Secure Connection",
  "Security Champions",
  "Security Policy",
  "Session Management",
  "Smart Devices",
  "SMS Phishing",
  "Social Engineering",
  "Social Media",
  "Spam",
  "Spearphishing",
  "Spoofed domains",
  "SSID",
  "Tailgating",
  "Travel Security",
  "Updates and Patches",
  "Vishing",
  "Whaling",
  "Wi-Fi",
  "Work Bytes",
  "WORKed",
  "Working Remotely",
  "XXE",
];

export const programResources: string[] = [
  "Emails",
  "Infographics",
  "Newsletters",
  "Posters",
  "Program plans and kits",
];

export const securityLevels: string[] = [
  "Low",
  "Medium",
  "High",
  "Critical"
];